### ISSUE TITLE
Settings being dropped after eclipse restart

### ISSUE THREAD

**Issue by zelenyhleb** [zelenyhleb/etape#1]
Settings being dropped after eclipse restart. PLEASE HELP!!!

**Comment by eparovyshnaya** [comment]
two cents:

- create a plug-in dev project by THE template
- edit _copyright_ test of the template
- _persist_ the change
- finish project creation or calcel it, we do not need this project actually
- open etape-dedicated Preferences
- _Copyright_ field is empty (even last time you saw it there was a not-blank value
 
I dare to anticipate _persisted_ copyright must appear to prefernces, as well as preferenced copyright must appear in template
